### PR TITLE
Add an entry for the PNR party

### PR DESCRIPTION
**Pull request by gpetit**
Add an entry for the PNR party

### CODE REVIEW

**Comment by nicolas-f** [comment]
Maybe use the link to the right extent http://noise-planet.org/map_noisecapture/noisecapture_party.html#13/47.7313/-2.5957/PNRGM_Elven

**Comment by gpetit** [comment]
Hum ... why not, but for the other 3 parties we did not added the extent in the link ?!

**Comment by nicolas-f** [comment]
It seems to work when we click on a link without specifying the extent. But not when we type the link. So it is ok.

**Comment by gpetit** [comment]
Thx

**Pull request merged**
