### PR TITLE
Add entry for ANQES future party

### PR DESCRIPTION
**Pull request by gpetit**
Add entry for ANQES future party

Also add the name of a german translator

### CODE REVIEW

**Comment by Picaut** [comment]
My preferred option should be to use 'Bootstrap Card' instead of full image (that includes text) to show the NoiseCapture Parties: https://getbootstrap.com/docs/4.0/components/card/
using font Awesome symbol, such as 'fa-map-marker', 'fa-calendar' and 'fa-hashtag'
and adding the logo of the event

**Comment by gpetit** [comment]
Ok @Picaut no problem. I will work on it on friday (tomorrow i'm at ecn)

**Comment by gpetit** [comment]
Here is the v2, using cards as asked by @Picaut 
Still open for discussions !

**Comment by gpetit** [comment]
Arf forgot to use  'fa-map-marker', 'fa-calendar' and 'fa-hashtag'
I'll try to update

**Comment by gpetit** [comment]
fa-icons are now used.
I also add an entry for FDS2017 party

**Comment by Picaut** [comment]
Just perfect!

**Comment by gpetit** [comment]
Thx

**Pull request merged**
