### PR TITLE
Add automatic refresh of measurements history

### PR DESCRIPTION
**Pull request by nicolas-f**
Add a checkbox to automatically navigate trough new measurements each 35 seconds

### CODE REVIEW

**Comment by nicolas-f** [comment]
Preview https://nicolas-f.github.io/NoisePlanet/map_noisecapture

**Comment by gpetit** [comment]
Nice job !

**Comment by nicolas-f** [comment]
Ok to merge ?

**Comment by Picaut** [comment]
yes

**Pull request merged**
