### PR TITLE
NoiseCapture Party html page

### PR DESCRIPTION
**Pull request by nicolas-f**
New webpage to display noisecapture party

**Do not merge** until geoserver has not been updated

### CODE REVIEW

**Comment by nicolas-f** [comment]
Preview https://nicolas-f.github.io/NoisePlanet/map_noisecapture/noisecapture_party.html

**Comment by nicolas-f** [comment]
What is the tag for the next digital week ?

**Comment by Picaut** [comment]
#SNDigitalWeek

**Comment by nicolas-f** [comment]
Checked on my side, ready to merge

**Comment by Picaut** [comment]
Let's go...

**Pull request merged**
